### ISSUE TITLE
Look into why this metre was not identified

### ISSUE THREAD

**Issue by shreevatsa** [shreevatsa/sanskrit#106]
https://twitter.com/GuruvayurappanR/status/1079049598889390080

https://groups.google.com/forum/m/#!msg/bvparishat/C0a-WPWKSsY/8e22Y1FxhP8J

Probably something broke while I was messing about with the data.

**Comment by sridatta1** [comment]
Duplicate of #87

**Comment by shreevatsa** [comment]
Oh this is embarrassing. (Thank you.) I'll try to take a few hours this weekend and get the project into at least a slightly better state.
