### ISSUE TITLE
bulk mode

### ISSUE THREAD

**Issue by gasyoun** [shreevatsa/sanskrit#125]
@shreevatsa was not there a bulk mode? How can I check http://gretil.sub.uni-goettingen.de/gretil/corpustei/transformations/html/sa_azvaghoSa-buddhacarita-alt.htm at once, please advise?

**Comment by shreevatsa** [comment]
Just remembered that I had implemented something like this and forgotten about it as it was still unfinished etc. But see http://sanskritmetres.appspot.com/fulltext — totally unsupported, please don't report bugs in it :-)

**Comment by gasyoun** [comment]
> Just remembered

And you kept silent for all these years? It works fast.

> totally unsupported, please don't report bugs in it 
Naiy, it can't be.

Can I ask the metres to be all capital or all small letters? 
```
Upajāti	25 (17.01%)
indravajrā	23 (15.65%)
vāṇī	11 (7.48%)
ārdrā	10 (6.80%)
kīrtiḥ	10 (6.80%)
bālā	10 (6.80%)
Puṣpitāgrā	9 (6.12%)
viparītākhyānikī	9 (6.12%)
śālā	7 (4.76%)
māyā	5 (3.40%)
upendravajrā	5 (3.40%)
ṛddhiḥ	4 (2.72%)
buddhiḥ	4 (2.72%)
ākhyānikī	4 (2.72%)
rāmā	2 (1.36%)
mālā	2 (1.36%)
śrī	1 (0.68%)
puṣpitāgrā	1 (0.68%)
yamanakam	1 (0.68%)
Mālinī	1 (0.68%)
visasi	1 (0.68%)
vainasam	1 (0.68%)
bhadrā	1 (0.68%)
```

**Comment by shreevatsa** [comment]
Closing as the bulk mode exists. Having all the metres be consistent (all capital / all lowercase) is good feedback, already tracked as #117
