### ISSUE TITLE
Rathoddhatā vs. Upajāti no IAST

### ISSUE THREAD

**Issue by gasyoun** [shreevatsa/sanskrit#129]
Rathoddhatā contains both devanagari and IAST.

Upajāti contains only devanagari.

![yatra](https://user-images.githubusercontent.com/80761/103180951-412d6180-48ac-11eb-90cc-dfbe4de56978.JPG)

http://sanskritmetres.appspot.com/fulltext

**Comment by shreevatsa** [comment]
Same as #41 (but the screenshot is helpful)
