### ISSUE TITLE
Provide link to https://github.com/shreevatsa/sanskrit/issues/new

### ISSUE THREAD

**Issue by vvasuki** [shreevatsa/sanskrit#71]
I find that it takes a minute or two to get here from http://sanskritmetres.appspot.com/identify (others who don't know where to look will find it tougher). It would be of great use if you linked to the source code and this issues page from http://sanskritmetres.appspot.com/identify

**Comment by vvasuki** [comment]
अधुनैव पश्यामि कश्चन सङ्केतो दत्त एवेति - http://i.imgur.com/QQtohUA.png । किञ्च http://i.imgur.com/WzLRJx8.png इत्यत्राऽपि स्यात्।

**Comment by shreevatsa** [comment]
Saving here for my future reference:

https://github.com/Yubico/developers.yubico.com/issues/new?title=Suggested%20edit%20for%20U2F/index

**Comment by shreevatsa** [comment]
Saving here for my future reference:

Can have a link like:

https://github.com/shreevatsa/sanskrit/issues/new?title=foo&body=foo%20bar%0Aline%202%0A%60%60%60%0Aoriginal%20input%0A%60%60%60

etc.

More params at: https://developer.github.com/v3/issues/

**Comment by gasyoun** [comment]
Totally agree. And it takes about 2 minutes to get from here to http://sanskritmetres.appspot.com/identify

**Comment by shreevatsa** [comment]
@gasyoun 2 minutes from where?

**Comment by gasyoun** [comment]
From Github, after the link is at README.md it's good, but long I was hunting for it before. Would love to see some new stats on Mahabharata and Ramayana, some bigger texts or an article from you based on what you have seen, maybe even at a conference?

**Comment by shreevatsa** [comment]
Ah ok. Just recently after many months I'm finding a bit of time each week to work on this; hopefully in another month after fixing some outstanding issues, I'll get back to looking stats. :-)

**Comment by gasyoun** [comment]
We are eagerly waiting anyway.
