### ISSUE TITLE
अन्तिमपादान्ते ऽस्थाने रक्तवर्णाङ्कनम्।

### ISSUE THREAD

**Issue by vvasuki** [shreevatsa/sanskrit#73]
http://i.imgur.com/IyWXUYo.png इत्यत्र चतुर्थपादस्यान्ते ऽस्ति गुरुर् यथेष्टम्। एवञ्चेदपि रक्तवर्णेन तदङ्कितम्।

बुद्धे ते शङ्करत्वं निमिषितनयने वीक्ष्य केचिद् व्यचिन्वन्
कारुण्याद् विष्णुमाहुर् जनहितकरणे प्राप्तरामानुजत्वम्।
मन्त्रैस् तन्त्रैश्च तत्त्वैर् ऋषिमतिविमलं सौम्यमध्वप्रकाशं
प्राहुः केचित् तथाऽस्तु प्रमुदितमनसां वल्लभोऽयं कथञ्चित्॥ इति पद्यम्

**Comment by shreevatsa** [comment]
This should be fixed now.

Unrelated: I've also pushed a new version (1g) which among other things also doesn't have the huge list of 1400+ metres, most of which were nonsensical. I deeply regret including them and leaving the website in that state for many months.
(I might bring them back as an option, after figuring out how to deal with them. They are of course still available in version 1f.)

**Comment by vvasuki** [comment]
2015-05-07 15:01 GMT-07:00 Shreevatsa <notifications@github.com>:

> most of which were nonsensical

​कथं तथा?​


> I deeply regret including them and leaving the website in that state for
> many months.

​कुतः? का हानिः?​




-- 
--
Vishvas /विश्वासः

**Comment by vvasuki** [comment]
अपि च श्लोकार्थेऽनुवर्तते दोषोऽयम् - http://i.imgur.com/Zq7Hh4V.png

**Comment by shreevatsa** [comment]
That is #17 still.

**Comment by vvasuki** [comment]
किञ्च, पादान्तलघोर् वार्ता भिन्ना, पद्यार्धलघोश् च भिन्ना।

**Comment by shreevatsa** [comment]
I was calling it "sama-pādānta-laghu" (end of even _pāda_-s = 2 and 4 = पद्यार्ध) as the second point there. Will get to it soon. :)
