### ISSUE TITLE
Highlight the "does not match" string in case of partial matches

### ISSUE THREAD

**Issue by vvasuki** [shreevatsa/sanskrit#74]
अन्यथा स्थूलाक्षरैर् लिखितं छन्दोनाम दृष्ट्वा सौष्ठवं मन्येत त्वरया जनः।

http://i.imgur.com/GiOUnJ7.png

**Comment by vvasuki** [comment]
रक्तवर्णे स्यात् "does not match" इति।

**Comment by gasyoun** [comment]
Red?

**Comment by vvasuki** [comment]
Ah! I was again fooled into thinking that the metre checked out  - https://www.facebook.com/groups/padyadhaaraa/permalink/390134337858042/ .

**Comment by shreevatsa** [comment]
I have made the "not" be bigger and in bold; take a look.

Some more aesthetic styling can still be done, but seems to serve the purpose for now.

**Comment by vvasuki** [comment]
LGTM, thanks
