### ISSUE TITLE
रथोद्धता metre identification

### ISSUE THREAD

**Issue by nangia** [shreevatsa/sanskrit#84]
I have an issue to report about the results for the following verse from rAmarakShastotram:
```
आत्तसज्जधनुषाविषुस्पृशावक्षयाशुगनिषङ्‌गसङि‌गनौ।
रक्षणाय मम रामलक्ष्मणावग्रतः पथि सदैव गच्छताम्‌॥
```

The issue is:
सङि‌गनौ is GLG. But this is identified incorrectly. See picture. 
<img width="266" alt="screen shot 2016-01-10 at 4 34 55 pm" src="https://cloud.githubusercontent.com/assets/1845657/12221237/1d089ca0-b7b8-11e5-9ed3-fd00e2e5e245.png">

[Please input the issue here]

**Comment by drdhaval2785** [comment]
@nangia 
Your input is wrong.
सङिगनौ is wrong. 
सङ्गिनौ is right.

When I entered सङ्गिनौ, it was found out well.
![capture](https://cloud.githubusercontent.com/assets/5755132/12221637/9684f874-b7c9-11e5-9123-d68e2ee9ae21.png)

**Comment by nangia** [comment]
You are right, @drdhaval2785 . Thanks for pointing my error.
