### ISSUE TITLE
Publish pip packages

### ISSUE THREAD

**Issue by vvasuki** [shreevatsa/sanskrit#98]
Some modules in this project should be separated out and published as pip packages. Eg: Those for transliteration and metre identification.

That will increase modularity, discoverability and simple usage (saving consumers a lot of trouble). This is something I learned by experience from my java/ scala work. I am specially interested in being able to use these modules in my own python code in the near future - so request prioritization.

**Comment by vvasuki** [comment]
The mallus seem to have some headway here: https://pypi.python.org/pypi/inexactsearch/1.0.2 , https://pypi.python.org/pypi/katapayadi/0.2.0 .

**Comment by shreevatsa** [comment]
Yes I agree. For example Arun split out even script-detection into a module of its own ([here](https://github.com/sanskrit/detect.py) / [here](https://github.com/sanskrit/detect.js)). Doing the same here and putting it on pip would be the next step… 

I cannot promise a date but will definitely get to this as soon as I can… I think the code has become quite messy and it needs a principled refactor (part of which is what you say), so this is definitely the first thing to do.

**Comment by gasyoun** [comment]
> script-detection into a module of its own

Yeah, it's a fine one, used it.

**Comment by vvasuki** [comment]
@shreevatsa I published aruNa's transliteration package - 'twas quite simple. <https://pypi.python.org/pypi/indic-transliteration> - you can switch or add to it as you please, and use it as an example for packaging the metre identifier.

**Comment by gasyoun** [comment]
> aruNa's transliteration package

It covers 3 of them?

**Comment by vvasuki** [comment]
> It covers 3 of them?
No - just python (which is what this thread is about).

**Comment by vvasuki** [comment]
अत्र चेत् स्वीकुर्याः सहकारम् साधयेयं कार्यमिदम्।

**Comment by shreevatsa** [comment]
Are there instructions for packaging a library into a form suitable for pip? Is this it: https://packaging.python.org/tutorials/distributing-packages/

**Comment by shreevatsa** [comment]
This one looks useful: https://python-packaging.readthedocs.io/en/latest/ -- ok I'll take a look.

**Comment by vvasuki** [comment]
It's done - https://github.com/sanskrit-coders/chandas/ . Please see thread on sanskrit-programmers mailing list as well.

**Comment by sridatta1** [comment]
In the Google groups thread there was a message on syllabification, here is a post on it by Anshuman Pandey https://pandey.github.io/posts/tokenize-indic-syllables-python.html
and the analyzer http://pandey.pythonanywhere.com/devsyll
Though there is some difference between graphical and phonetic syllables and they are not the same in all cases
